### ISSUE TITLE
dalao，系统日志 一直出现错误提示

### ISSUE THREAD

**Issue by vi-si** [mapdio/R7800-Openwrt-with-NSS#1]
Sun Feb 21 20:27:10 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:29:12 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:31:05 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:31:33 2021 authpriv.info dropbear[12620]: Child connection from 192.168.1.165:1797
Sun Feb 21 20:31:34 2021 authpriv.notice dropbear[12620]: Password auth succeeded for 'root' from 192.168.1.165:1797
Sun Feb 21 20:32:06 2021 daemon.err uhttpd[1503]: cat: can't open '/etc/bench.log': No such file or directory
Sun Feb 21 20:33:03 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:35:11 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:37:09 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:39:06 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:41:19 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:43:12 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:45:15 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:47:23 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:47:25 2021 daemon.err uhttpd[1503]: cat: can't open '/etc/bench.log': No such file or directory
Sun Feb 21 20:48:00 2021 daemon.err uhttpd[1503]: cat: can't open '/etc/bench.log': No such file or directory
Sun Feb 21 20:48:21 2021 daemon.err uhttpd[1503]: cat: can't open '/etc/bench.log': No such file or directory
Sun Feb 21 20:49:26 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:51:34 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:53:27 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:55:29 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:57:32 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 20:59:35 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 21:01:38 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 21:03:41 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 21:05:39 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 21:07:52 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 21:09:50 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 21:11:52 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Sun Feb 21 21:14:06 2021 daemon.err odhcp6c[1946]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)

**Comment by mapdio** [comment]
1. 自行在/etc/下创建bench.log文件，内容随意字符都可以，是CPU跑分记录，不建也行，不影响使用
2. daemon.err odhcp6c，可能是本地网络不支持ipv6或者不能正确获取ipv6地址，可以接口删除wan6，或者winscp修改/etc/config/network文件，删除config interface 'wan6'的设置段，或者在后面添加 option auto '0'

**Comment by vi-si** [comment]
**感谢回复！**
