### ISSUE TITLE
不支持firewall fullcone nat

### ISSUE THREAD

**Issue by wuyiliang0** [mapdio/R7800-Openwrt-with-NSS#2]
1、无法开启fullcone nat，启动firewall报unknown option fullcone ‘1’
2、upnp无法打开，日志报can't find /var/upnp.leases
3、wifi运行半小时就挂了

**Comment by Hsen889** [comment]
一楼遇到的故障问题，在我这边测试下来也同样存在。另外再补充2个BUG：一是网络VLAN交换机项下打开出错，二是LUCI在web界面经常出现异常，无法保存应用。
